### ISSUE TITLE
Add SSH Key to github and clone repo linux training

### ISSUE THREAD

**Issue by GraphicDThanh** [GraphicDThanh/hung-do-linux-training#4]
(please add steps you do on this task here)

**Comment by meovan07** [comment]
Solved ✅ 
Step 1: Checking for the existing SSH key. Following the [check-existing-ssh-key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/checking-for-existing-ssh-keys).
Step 2: In case there is no existing SSH key. Generating a new SSH Key following [Generating-new-key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).
Step 3: Adding SSH to account Github. Following [Add-SSH-key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account). At the end of this step, everything is done for setting up the SSH key.
Step 4: Cloning a repository. Following [clone-repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository).

**Comment by thanhnguyen-agilityio** [comment]
Thx for the guide @meovan07 . Next time, please feel free to put the content to issue's description.

**Comment by meovan07** [comment]
> Thx for the guide @meovan07 . Next time, please feel free to put the content to issue's description.

Noted. thanks for comment
