### ISSUE TITLE
Visual Studio Code is not recognized "git" commands

### ISSUE THREAD

**Issue by GraphicDThanh** [GraphicDThanh/hung-do-linux-training#6]
Step 1: Make sure to install Git on Pc
Step 2:Check git.path in Visual Studio Code to make sure the correct path for git.
In case of the wrong path check out [this](https://stackoverflow.com/questions/4492979/git-is-not-recognized-as-an-internal-or-external-command).
Step 3: Check the Visual Studio Code again. If still not working, try reinstalling git and restart pc.

**Comment by GraphicDThanh** [comment]
Please try by yourself to fix this error, seem it happen on Window only.
Take a look at these links for a chance:

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git 

https://stackoverflow.com/questions/4492979/git-is-not-recognized-as-an-internal-or-external-command 
Good luck :D

**Comment by meovan07** [comment]
Solved ✅ 
Step 1: Make sure to install Git on Pc
Step 2:Check git.path in Visual Studio Code to make sure the correct path for git.
In case of the wrong path check out: https://stackoverflow.com/questions/4492979/git-is-not-recognized-as-an-internal-or-external-command.
Step 3: Check the Visual Studio Code again. If still not working, try reinstalling git and restart pc.
